# Generated by Django 5.0 on 2023-12-14 21:22

import core.models
import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_funcionariomodel_instagram_funcionariomodel_twitter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionariomodel',
            name='imagem',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to=core.models.get_file_path, variations={'thumb': {'crop': True, 'height': 480, 'width': 480}}, verbose_name='Imagem'),
        ),
    ]
